<?php
// ============================================
// EXCLUSIVEGRADE - CONFIGURATION
// ============================================
// DO NOT EDIT THIS FILE
// EDIT ONLY THE .env FILE
// ============================================

// Load environment variables from .env file
$envFile = __DIR__ . '/.env';
if (file_exists($envFile)) {
    $lines = file($envFile);
    foreach ($lines as $line) {
        $line = trim($line);
        if (empty($line) || strpos($line, '#') === 0) continue;
        if (strpos($line, '=') !== false) {
            list($key, $value) = explode('=', $line, 2);
            putenv("$key=$value");
            $_ENV[$key] = $value;
        }
    }
}

// Database
define('DB_HOST', getenv('DB_HOST') ?: 'localhost');
define('DB_NAME', getenv('DB_NAME') ?: 'exclusivegrade');
define('DB_USER', getenv('DB_USER') ?: 'root');
define('DB_PASS', getenv('DB_PASS') ?: '');

// URLs
define('BASE_URL', getenv('BASE_URL') ?: 'http://localhost/exclusivegrade');
define('API_URL', getenv('API_URL') ?: BASE_URL . '/backend/api');

// Paystack
define('PAYSTACK_PUBLIC_KEY', getenv('PAYSTACK_PUBLIC_KEY') ?: '');
define('PAYSTACK_SECRET_KEY', getenv('PAYSTACK_SECRET_KEY') ?: '');

// OpenAI
define('OPENAI_API_KEY', getenv('OPENAI_API_KEY') ?: '');

// Email
define('SMTP_HOST', getenv('SMTP_HOST') ?: '');
define('SMTP_PORT', (int)(getenv('SMTP_PORT') ?: 587));
define('SMTP_USER', getenv('SMTP_USER') ?: '');
define('SMTP_PASS', getenv('SMTP_PASS') ?: '');

// App
define('APP_NAME', getenv('APP_NAME') ?: 'ExclusiveGrade');
define('APP_ENV', getenv('APP_ENV') ?: 'development');
define('APP_DEBUG', getenv('APP_DEBUG') === 'true');
define('TOKEN_EXPIRY_HOURS', (int)(getenv('TOKEN_EXPIRY_HOURS') ?: 720));
define('BCRYPT_COST', (int)(getenv('BCRYPT_COST') ?: 12));

// Plan Limits
define('PLAN_LIMITS', [
    'starter' => [
        'students' => (int)(getenv('STARTER_STUDENT_LIMIT') ?: 10),
        'teachers' => (int)(getenv('STARTER_TEACHER_LIMIT') ?: 2)
    ],
    'pro' => [
        'students' => (int)(getenv('PRO_STUDENT_LIMIT') ?: 200),
        'teachers' => (int)(getenv('PRO_TEACHER_LIMIT') ?: 10)
    ],
    'enterprise' => [
        'students' => PHP_INT_MAX,
        'teachers' => PHP_INT_MAX
    ]
]);

// PIN Prices
define('PIN_PRICES', [
    'starter' => (int)(getenv('PIN_PRICE_STARTER') ?: 100),
    'pro' => (int)(getenv('PIN_PRICE_PRO') ?: 80),
    'enterprise' => (int)(getenv('PIN_PRICE_ENTERPRISE') ?: 50)
]);

// PIN Defaults
define('DEFAULT_PIN_USAGE_LIMIT', (int)(getenv('DEFAULT_PIN_USAGE_LIMIT') ?: 3));
define('DEFAULT_PIN_EXPIRY_DAYS', (int)(getenv('DEFAULT_PIN_EXPIRY_DAYS') ?: 365));

// Subscription
define('PRO_MONTHLY', (int)(getenv('PRO_MONTHLY') ?: 10000));
define('PRO_ANNUAL', (int)(getenv('PRO_ANNUAL') ?: 80000));
define('ENTERPRISE_MONTHLY', (int)(getenv('ENTERPRISE_MONTHLY') ?: 25000));
define('ENTERPRISE_ANNUAL', (int)(getenv('ENTERPRISE_ANNUAL') ?: 240000));

// AI Notes
define('AI_NOTES_PRO_LIMIT', (int)(getenv('AI_NOTES_PRO_LIMIT') ?: 20));
define('AI_NOTES_PRICE', (int)(getenv('AI_NOTES_PRICE') ?: 100));

// Helper functions
function getPlanLimit($plan, $type) {
    $limits = PLAN_LIMITS[$plan] ?? PLAN_LIMITS['starter'];
    return $limits[$type] ?? 0;
}

function getPinPrice($plan) {
    return PIN_PRICES[$plan] ?? PIN_PRICES['starter'];
}